### ISSUE TITLE
Update "Apply for job" to directly use Adapt API

### ISSUE THREAD

**Issue by davedx** [laradg/magno-todo#66]
We would like applications for jobs to use the Adapt API instead of sending an email.

* Identify which fields are required. Either use existing fields, make defaults, or if really necessary add a new field in the front end
* If candidate (n == 1) is found using get_candidate endpoint, use their candidate ID to make an application. Email application to Daxtra with subject "No further processing required"
* If candidate is not found, email application to Daxtra with subject "[JOB_ID] New application"
* Ensure application receives correct feedback (whether request failed or not)

**Comment by laradg** [comment]
Looks like this was completed already
